# Generated by Django 3.2 on 2022-11-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='wish_movie',
            field=models.BooleanField(default=False),
        ),
    ]
