# Generated by Django 3.2 on 2022-11-23 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_wish_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='wish_movie',
        ),
    ]
