# Generated by Django 3.2 on 2022-11-23 01:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_remove_movie_wish_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='wish_movie',
            field=models.ManyToManyField(related_name='wishmovie', to=settings.AUTH_USER_MODEL),
        ),
    ]
