# Generated by Django 3.2 on 2022-11-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_wish_movie'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wish_movie',
            field=models.ManyToManyField(related_name='wishmovie', to='movies.Movie'),
        ),
    ]
